name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test --verbose
    - name: Build
      run: cargo build --release
    - uses: actions/upload-artifact@v2
      with:
        name: my-binary
        path: target/release/raspi-fan-controller
create-release:
  needs: build
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v2
  - uses: actions/download-artifact@v2
    with:
      name: my-binary
      path: path/to/artifact
  - name: Create Release
    uses: softprops/action-gh-release@v1
    with:
    files: target/release/raspi-fan-controller
  env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
